name: Shared Maven CI

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        type: string
        default: '25'
      maven-goals:
        description: 'Maven goals to run'
        required: false
        type: string
        default: 'clean verify'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@main
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn --batch-mode --no-transfer-progress ${{ inputs.maven-goals }}

      - name: Extract Final Artifact Name from POM
        if: github.event_name == 'release'
        id: pom-info
        run: |
          FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
          echo "jar_name=${FINAL_NAME}" >> "$GITHUB_OUTPUT"

      - name: Upload JAR to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@master
        with:
          files: target/${{ steps.pom-info.outputs.jar_name }}.jar
